// <auto-generated />
namespace Cloud_Index_Calculator_ITLA.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatinglettertype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatinglettertype));
        
        string IMigrationMetadata.Id
        {
            get { return "201608112247310_updatinglettertype"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
